### ISSUE TITLE
Support for GTM environments

### ISSUE THREAD

**Issue by Bernd-Altstaetter** [stafyniaksacha/vite-plugin-radar#22]
Currently it is not possible to define the GTM environment.
See https://support.google.com/tagmanager/answer/6311518?hl=en# for more information about environments.

**Comment by Bernd-Altstaetter** [comment]
Since my pull request was merged, i guess this issue should be resolved in the next release.

**Comment by Bernd-Altstaetter** [comment]
@stafyniaksacha when can we expect a new version that contains this change?

**Comment by stafyniaksacha** [comment]
@Bernd-Altstaetter It's released in v0.9.1!
